'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,getattr,
hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";import{fabric}from"./com.fabricjs.js";import*as gp from"./GraphParams.js";var __name__="__main__";export var orthoWidth=1E3;export var orthoHeight=750;export var fieldHeight=650;var __left0__=tuple([13,27,32]);export var enter=__left0__[0];export var esc=
__left0__[1];export var space=__left0__[2];window.onkeydown=function __lambda__(event){return event.keyCode!=space};export var Attribute=__class__("Attribute",[object],{__module__:__name__,get __init__(){return __get__(this,function(self,game){self.game=game;self.game.attributes.append(self);self.install();self.reset()})},get reset(){return __get__(this,function(self){self.game.t0=+new Date/1E3;self.commit()})},get move(){return __get__(this,function(self){})},get interact(){return __get__(this,function(self){})},
get commit(){return __get__(this,function(self){})}});export var Cycle=__class__("Cycle",[Attribute],{__module__:__name__,get __init__(){return __get__(this,function(self,game,n){Attribute.__init__(self,game);self.n=n;self.radius=self.game.R[self.n];var C=list(self.game.C[n]);self.Cx=C[0];self.Cy=C[1];self.color=self.game.CAMAIEU[self.n];self.game.initialize_polygon(self.n)})},get install(){return __get__(this,function(self){self.circle=new fabric.Circle(dict({"radius":self.game.R[self.n],"originX":"center",
"originY":"center","angle":0,"startAngle":0,"endAngle":2*Math.PI,"stroke":self.game.linecolor,"strokeWidth":1,"fill":""}));self.Rays=[];var S=list(self.game.S[self.n]);for(var Sk of S){var Sk=list(Sk);self.Rays_coords=[self.Cx,self.Cy,Sk[0],Sk[1]];self.Rays.append(new fabric.Line(self.Rays_coords,dict({"stroke":self.color})))}self.Edges=[];var S=list(self.game.S[self.n]);for(var k=0;k<self.game.N[self.n];k++){var S1=list(S[k]);var S2=list(S[__mod__(k+1,self.game.N[self.n])]);self.Edge_coords=[S1[0],
S1[1],S2[0],S2[1]];self.Edges.append(new fabric.Line(self.Edge_coords,dict({"stroke":self.color})))}return null})},get reset(){return __get__(this,function(self,vX,vY,x,y){if(typeof vX=="undefined"||vX!=null&&vX.hasOwnProperty("__kwargtrans__"))var vX=0;if(typeof vY=="undefined"||vY!=null&&vY.hasOwnProperty("__kwargtrans__"))var vY=0;if(typeof x=="undefined"||x!=null&&x.hasOwnProperty("__kwargtrans__"))var x=0;if(typeof y=="undefined"||y!=null&&y.hasOwnProperty("__kwargtrans__"))var y=0;if(arguments.length){var __ilastarg0__=
arguments.length-1;if(arguments[__ilastarg0__]&&arguments[__ilastarg0__].hasOwnProperty("__kwargtrans__")){var __allkwargs0__=arguments[__ilastarg0__--];for(var __attrib0__ in __allkwargs0__)switch(__attrib0__){case "self":var self=__allkwargs0__[__attrib0__];break;case "vX":var vX=__allkwargs0__[__attrib0__];break;case "vY":var vY=__allkwargs0__[__attrib0__];break;case "x":var x=__allkwargs0__[__attrib0__];break;case "y":var y=__allkwargs0__[__attrib0__];break}}}else;self.vX=vX;self.vY=vY;self.x=
x;self.y=y;Attribute.reset(self)})},get move(){return __get__(this,function(self){self.x+=self.vX*self.game.deltaT;self.y+=self.vY*self.game.deltaT})},get commit(){return __get__(this,function(self){self.install();self.radius=self.game.R[self.n];self.circle.radius=self.radius;if(self.n!=0)self.game.move_polygon(self.n);var C=list(self.game.C[self.n]);self.Cx=C[0];self.Cy=C[1];self.circle.left=self.Cx;self.circle.top=self.Cy;return null})},get draw(){return __get__(this,function(self){var drawCircle=
self.n>0&&self.game.SecondaryCyclesVisible||self.n==0&&self.game.MainCycleVisible;if(drawCircle)self.game.canvas.add(self.circle);for(var r of self.Rays)self.game.canvas.add(r);for(var e of self.Edges)self.game.canvas.add(e)})}});export var Spot=__class__("Spot",[Attribute],{__module__:__name__,get __init__(){return __get__(this,function(self,game,n){Attribute.__init__(self,game);self.size=self.game.RS_radius;self.n=n;self.color=self.game.CAMAIEU[self.n]})},get install(){return __get__(this,function(self){self.image=
new fabric.Circle(dict({"radius":self.size,"originX":"center","originY":"center","angle":0,"startAngle":0,"endAngle":2*Math.PI,"stroke":"white","strokeWidth":1,"fill":self.color}))})},get RS_coords_0(){return __get__(this,function(self,x1,y1,x2,y2){return tuple([(x1+x2)/2,(y1+y2)/2])})},get RS_coords(){return __get__(this,function(self,x1,y1,x2,y2){var A=1/(Math.exp(1/self.game.feel)-1);var s=A*(Math.exp(self.tp/self.game.feel)-1);return tuple([(1-s)*x2+s*x1,(1-s)*y2+s*y1])})},get pulse_relative_time(){return __get__(this,
function(self,n,tn,jn){if(self.game.irregular){var durations=tuple([]);for(var i=0;i<self.N[n]-1;i++)durations+=tuple([(self.game.voicings[n][i+1]-self.game.voicings[n][i])*self.game.T[n]]);durations+=tuple([(1-self.game.voicings[n][self.game.N[n]-1])*self.game.T[n]]);var tp=__mod__(tn-self.game.voicings[n][jn]*self.game.T[n],durations[jn])/durations[jn]}else var tp=__mod__(self.game.t,self.game.T[n]/self.game.N[n])*self.game.N[n]/self.game.T[n];return tp})},get reset(){return __get__(this,function(self){if(arguments.length){var __ilastarg0__=
arguments.length-1;if(arguments[__ilastarg0__]&&arguments[__ilastarg0__].hasOwnProperty("__kwargtrans__")){var __allkwargs0__=arguments[__ilastarg0__--];for(var __attrib0__ in __allkwargs0__)switch(__attrib0__){case "self":var self=__allkwargs0__[__attrib0__];break}}}else;self.x=self.game.mainCycle.Cx;self.y=self.game.mainCycle.Cy+self.game.mainCycle.radius;Attribute.reset(self)})},get move(){return __get__(this,function(self){var __left0__=self.game.pulse_index_in_cycle(self.n);var tn=__left0__[0];
var jn=__left0__[1];self.tp=self.pulse_relative_time(self.n,tn,jn);var S1=list(self.game.S[self.n][self.game.N[self.n]-jn-1]);var S2=list(self.game.S[self.n][__mod__(self.game.N[self.n]-jn,self.game.N[self.n])]);var RS=list(self.RS_coords(S1[0],S1[1],S2[0],S2[1]));self.x=RS[0];self.y=RS[1]})},get commit(){return __get__(this,function(self){self.image.left=self.x;self.image.top=self.y})},get draw(){return __get__(this,function(self){self.game.canvas.add(self.image)})}});export var TimeFluxSpot=__class__("TimeFluxSpot",
[Attribute],{__module__:__name__,get __init__(){return __get__(this,function(self,game){Attribute.__init__(self,game);self.radius=.007*self.game.canvasWidth})},get install(){return __get__(this,function(self){self.image=new fabric.Circle(dict({"radius":self.radius,"originX":"center","originY":"center","angle":0,"startAngle":0,"endAngle":2*Math.PI,"stroke":"white","strokeWidth":1,"fill":"white"}))})},get reset(){return __get__(this,function(self){if(arguments.length){var __ilastarg0__=arguments.length-
1;if(arguments[__ilastarg0__]&&arguments[__ilastarg0__].hasOwnProperty("__kwargtrans__")){var __allkwargs0__=arguments[__ilastarg0__--];for(var __attrib0__ in __allkwargs0__)switch(__attrib0__){case "self":var self=__allkwargs0__[__attrib0__];break}}}else;self.x=self.game.mainCycle.Cx;self.y=self.game.mainCycle.Cy+self.game.mainCycle.radius;Attribute.reset(self)})},get move(){return __get__(this,function(self){self.x=self.game.mainCycle.radius*Math.cos(self.game.omega[0]*self.game.t+self.game.q0)+
self.game.mainCycle.Cx;self.y=-self.game.mainCycle.radius*Math.sin(self.game.omega[0]*self.game.t+self.game.q0)+self.game.mainCycle.Cy})},get commit(){return __get__(this,function(self){self.image.left=self.x;self.image.top=self.y})},get draw(){return __get__(this,function(self){self.game.canvas.add(self.image)})}});export var Game=__class__("Game",[object],{__module__:__name__,get __init__(){return __get__(this,function(self,bpm,voicings,mode,feel,graph_params,path2wav){if(typeof path2wav=="undefined"||
path2wav!=null&&path2wav.hasOwnProperty("__kwargtrans__"))var path2wav="./temp/";self.serviceIndex=Math.random()>.5?1:0;self.pause=false;self.keyCode=null;self.textFrame=document.getElementById("text_frame");self.canvasFrame=document.getElementById("canvas_frame");self.buttonsFrame=document.getElementById("buttons_frame");self.memo=document.getElementById("memo");self.aspectRatio=1;self.topMargin=100;self.canvas=new fabric.Canvas("canvas",dict({"backgroundColor":"black","originX":"center","originY":"center"}));
self.canvas.onWindowDraw=self.draw;self.canvas.lineWidth=2;self.canvas.clear();self.pageWidth=window.innerWidth;self.pageHeight=window.innerHeight;self.textTop=0;if(self.pageHeight>1.2*self.pageWidth){self.canvasHeight=self.pageHeight;self.canvasTop=self.textTop+self.topMargin}else{self.canvasHeight=.7*self.pageHeight;self.canvasTop=self.textTop+self.topMargin}self.canvasWidth=self.aspectRatio*self.canvasHeight;self.canvasLeft=.5*(self.pageWidth-self.canvasWidth);self.WIDTH=self.canvasWidth;self.HEIGHT=
self.canvasHeight;self.dt=.02;self.jn=0;self.get_graphic_parameters(graph_params);self.mode=mode;self.bpm=bpm;if(py_typeof(voicings[0])==int){self.N=voicings;self.irregular=false}else{self.voicings=voicings;self.init_N();self.irregular=true}self.S=[];self.initialize_cycles();self.cycle=[];self.Polygon=[-1]*len(self.N);self.Sound=[-1]*len(self.N);self.enlarge=5/4;self.Vertex1color="red";self.R2TFS_ratio=20;self.TFS_fill="#EAF3FB";self.TFS_outline="#A2B5C7";self.q0=1.5*Math.PI;self.R2RS_ratio=1;self.feel=
feel;self.TFS_radius=.007*self.canvasWidth;self.RS_radius=self.TFS_radius/self.R2RS_ratio;self.attributes=[];self.Cycles=[];self.RhythmSpots=[];for(var n=0;n<len(self.N);n++)self.Cycles.append(Cycle(self,n));self.mainCycle=self.Cycles[0];for(var n=0;n<len(self.N);n++)self.RhythmSpots.append(Spot(self,n));self.TFS=TimeFluxSpot(self);window.setInterval(self.py_update,20);window.setInterval(self.draw,20);self.ac=new window.AudioContext;self.time=+new Date/1E3;self.t0=self.time;self.t=self.time-self.t0;
var beep=document.getElementById("beep");self.setupSample();self.playSample();window.onresize=self.resize;self.resize();self.install()})},get getFile(){return __get__(this,async function(self,filePath){var url="https://upload.wikimedia.org/wikipedia/en/transcoded/d/dc/Strawberry_Fields_Forever_%28Beatles_song_-_sample%29.ogg/Strawberry_Fields_Forever_%28Beatles_song_-_sample%29.ogg.mp3";var response=await fetch(filePath);var arrayBuffer=await response.arrayBuffer();var audioBuffer=await self.ac.decodeAudioData(arrayBuffer);
return audioBuffer})},get setupSample(){return __get__(this,async function(self){var path2sounds="./sounds/";self.sample=[];for(var n of self.N){var filePath=path2sounds+"beep_"+str(n)+".wav";self.sample.append(await self.getFile(filePath))}return null})},get setupSample_(){return __get__(this,async function(self){var path2sounds="./sounds/";var filePath=path2sounds+"beep_8.wav";self.sample=await self.getFile(filePath);return null})},get playSample(){return __get__(this,function(self,n){if(typeof n==
"undefined"||n!=null&&n.hasOwnProperty("__kwargtrans__"))var n=0;var source=self.ac.createBufferSource();source.buffer=self.sample[n];source.connect(self.ac.destination);source.start(0);return null})},get playSample_(){return __get__(this,function(self){self.source.start(0);return null})},get beep(){return __get__(this,function(self,n){var __left0__=self.pulse_index_in_cycle(n);var tn=__left0__[0];var jn=__left0__[1];if(self.j[n]!=jn){if(n==0)self.memo.innerHTML="SHOOOOT!!!!";self.playSample(n);self.j[n]=
jn}else if(n==0)self.memo.innerHTML=str(self.j[n]);return null})},get install(){return __get__(this,function(self){for(var attribute of self.attributes)attribute.install()})},get mouseOrTouch(){return __get__(this,function(self,key,down){if(down)if(key=="space")self.keyCode=space;else if(key=="enter")self.keyCode=enter;else self.keyCode=ord(key);else self.keyCode=null})},get py_update(){return __get__(this,function(self){var oldTime=self.t;self.time=+new Date/1E3;self.t=self.time-self.t0;self.deltaT=
self.t-oldTime;self.update_cycle_parameters();if(self.mode=="common beat")self.beep(0);else for(var n=0;n<len(self.N);n++)self.beep(n);if(self.pause)if(self.keyCode==space)self.pause=false;else{if(self.keyCode==enter)self.scoreboard.reset()}else{for(var attribute of self.attributes)attribute.move();for(var attribute of self.attributes)attribute.interact();for(var attribute of self.attributes)attribute.commit()}})},get scored(){return __get__(this,function(self,playerIndex){self.scoreboard.increment(playerIndex);
self.serviceIndex=1-playerIndex;for(var paddle of self.paddles)paddle.reset();self.ball.reset();self.pause=true})},get commit(){return __get__(this,function(self){for(var attribute of self.attributes)attribute.commit()})},get draw(){return __get__(this,function(self){self.canvas.clear();for(var attribute of self.attributes)attribute.draw()})},get resize(){return __get__(this,function(self){self.pageWidth=window.innerWidth;self.pageHeight=window.innerHeight;self.textTop=0;if(self.pageHeight>1.2*self.pageWidth){self.canvasHeight=
self.pageHeight;self.canvasTop=self.textTop+self.topMargin}else{self.canvasHeight=.7*self.pageHeight;self.canvasTop=self.textTop+self.topMargin}self.canvasWidth=self.aspectRatio*self.canvasHeight;self.canvasLeft=.5*(self.pageWidth-self.canvasWidth);self.buttonsTop=self.canvasTop+self.canvasHeight+50;self.buttonsWidth=500;self.textFrame.style.top=self.textTop;self.textFrame.style.left=self.canvasLeft+.05*self.canvasWidth;self.textFrame.style.width=.9*self.canvasWidth;self.canvasFrame.style.top=self.canvasTop;
self.canvasFrame.style.left=self.canvasLeft;self.canvas.setDimensions(dict({"width":self.canvasWidth,"height":self.canvasHeight}));self.buttonsFrame.style.top=self.buttonsTop;self.buttonsFrame.style.left=.5*(self.pageWidth-self.buttonsWidth);self.buttonsFrame.style.width=self.canvasWidth;self.WIDTH=self.canvasWidth;self.HEIGHT=self.canvasHeight;self.update_cycle_parameters();for(var n=0;n<len(self.N);n++)self.move_polygon(n);self.install();self.commit();self.draw()})},get initialize_cycles(){return __get__(this,
function(self){self.T=[];self.R=[];self.C=[];self.omega=[];self.j=[];var n=0;self.T.append(self.N[n]*60/self.bpm);self.R.append(.28*min(self.WIDTH,self.HEIGHT));self.C.append(tuple([self.WIDTH/2,self.HEIGHT/2]));self.omega.append(-2*Math.PI/self.T[n]);self.j.append(0);for(var n=1;n<len(self.N);n++)if(self.mode=="common beat"){self.T.append(self.N[n]*60/self.bpm);self.R.append(self.N[n]/self.N[0]*self.R[0]);self.omega.append(2*Math.PI/self.T[n]+self.omega[0]);self.C.append(self.instant_center(n,0));
self.j.append(0)}else if(self.mode=="common cycle"){self.T.append(self.T[0]);self.R.append(self.R[0]);self.omega.append(self.omega[0]);self.C.append(self.C[0]);self.j.append(0)}return null})},get update_cycle_parameters_(){return __get__(this,function(self){for(var n=0;n<len(self.N);n++){self.T[n]=self.N[n]*60/self.bpm;if(n==0)self.R[n]=.28*min(self.WIDTH,self.HEIGHT);else self.R[n]=.28*min(self.WIDTH,self.HEIGHT);self.C[n]=tuple([self.WIDTH/2,self.HEIGHT/2]);self.omega[n]=-2*Math.PI/self.T[n]}return null})},
get update_cycle_parameters(){return __get__(this,function(self){var n=0;self.T[n]=self.N[n]*60/self.bpm;self.R[n]=.28*min(self.WIDTH,self.HEIGHT);self.C[n]=tuple([self.WIDTH/2,self.HEIGHT/2]);self.omega[n]=-2*Math.PI/self.T[n];for(var n=1;n<len(self.N);n++)if(self.mode=="common beat"){self.T[n]=self.N[n]*60/self.bpm;self.R[n]=self.N[n]/self.N[0]*self.R[0];self.omega[n]=2*Math.PI/self.T[n]+self.omega[0];self.C[n]=self.instant_center(n,self.t)}else if(self.mode=="common cycle"){self.T[n]=self.T[0];
self.R[n]=self.R[0];self.omega[n]=self.omega[0];self.C[n]=self.C[0]}return null})},get instant_center(){return __get__(this,function(self,n,t){var q=self.instant_angle(self.omega[0],t,self.q0);var Cn=tuple([self.C[0][0]+(self.R[0]-self.R[n])*Math.cos(q),self.C[0][1]+(self.R[0]-self.R[n])*Math.sin(q)]);var Cn=self.convert_to_frame_coordinates(Cn[0],Cn[1]);return Cn})},get instant_angle(){return __get__(this,function(self,omega,t,q0){return omega*t+q0})},get initialize_main_cycle(){return __get__(this,
function(self){var n=0;self.T.append(self.N[n]*60/self.bpm);self.R.append(.28*min(self.WIDTH,self.HEIGHT));self.C.append(tuple([self.WIDTH/2,self.HEIGHT/2]));self.omega.append(-2*Math.PI/self.T[n]);self.TFS_radius=self.R[n]/self.R2TFS_ratio;self.RS_radius=self.R[n]/self.R2RS_ratio;self.initialize_polygon(n);return null})},get init_N(){return __get__(this,function(self){self.N=[];for(var voicing of self.voicings)self.N.append(len(voicing));return null})},get initialize_polygon(){return __get__(this,
function(self,n){var S=[];for(var k=0;k<self.N[n];k++){var Sk=self.calculate_vertex_k_position(n,k,self.omega[n],0);S.append(Sk)}self.S.append(S);return null})},get move_polygon(){return __get__(this,function(self,n){var S=[];var t=0;if(self.mode=="common beat"&&n!=0)var t=self.t;for(var k=0;k<self.N[n];k++){var Sk=self.calculate_vertex_k_position(n,k,self.omega[n],t);S.append(Sk)}self.S[n]=list(S);return null})},get pulse_index_in_cycle(){return __get__(this,function(self,n){var N=self.N[n];var tn=
__mod__(self.t,self.T[n]);var jn=0|Math.floor(tn*N/self.T[n]);return tuple([tn,jn])})},get beep_(){return __get__(this,function(self,n){var __left0__=self.pulse_index_in_cycle(n);var tn=__left0__[0];var jn=__left0__[1];if(n==0)var sound=self.sound0;else if(n==1)var sound=self.sound1;else if(n==2)var sound=self.sound2;if(self.irregular)if(jn>0)var beep_conditions=tn-self.voicings[n][jn]*self.T[n]<=self.dt;else var beep_conditions=false;else var beep_conditions=__mod__(self.t,self.T[n]/self.N[n])<=
self.dt;if(tn<=self.dt||beep_conditions){sound.pause();sound.currentTime=0;sound.play()}return null})},get get_graphic_parameters(){return __get__(this,function(self,graph_params){self.background=graph_params["background"];self.CAMAIEU=graph_params["CAMAIEU"];self.linecolor=graph_params["linecolor"];self.R2TFS_ratio=graph_params["R2TFS_ratio"];self.TFS_fill=graph_params["TFS_fill"];self.TFS_outline=graph_params["TFS_outline"];self.R2RS_ration=graph_params["R2RS_ratio"];self.enlarge=graph_params["enlarge"];
self.Vertex1color=graph_params["Vertex1color"];self.MainCycleVisible=graph_params["MainCycleVisible"];self.SecondaryCyclesVisible=graph_params["SecondaryCyclesVisible"];return null})},get convert_to_frame_coordinates(){return __get__(this,function(self,x,y){return tuple([x,self.HEIGHT-y])})},get convert_to_relative_coordinates(){return __get__(this,function(self,x,y){return tuple([x,self.HEIGHT-y])})},get calculate_vertex_k_position(){return __get__(this,function(self,n,k,omega,t){var center=self.convert_to_relative_coordinates(...self.C[n]);
if(!self.irregular){var beta=2*Math.PI/self.N[n];var Sk=tuple([center[0]+self.R[n]*Math.cos(omega*t+k*beta+self.q0),center[1]+self.R[n]*Math.sin(omega*t+k*beta+self.q0)])}else var Sk=tuple([center[0]+self.R[n]*Math.cos(omega*t-self.voicings[n][__mod__(-k,self.N[n])]*2*Math.PI+self.q0),center[1]+self.R[n]*Math.sin(omega*t-self.voicings[n][__mod__(-k,self.N[n])]*2*Math.PI+self.q0)]);var Sk=self.convert_to_frame_coordinates(...Sk);return Sk})},get display_canvas_position(){return __get__(this,function(self){var text2display=
"pageWidth = {}\tpageHeight = {}\n".format(self.pageWidth,self.pageHeight);text2display+="canvasWidth = {}\tcanvasHeight = {}\n".format(self.canvasWidth,self.canvasHeight);text2display+="canvasLeft = {}\tcanvasTop = {}".format(self.canvasLeft,self.canvasTop);self.memo.innerHTML=text2display;return null})},get scaleX(){return __get__(this,function(self,x){return x*(self.canvas.width/orthoWidth)})},get scaleY(){return __get__(this,function(self,y){return y*(self.canvas.height/orthoHeight)})},get orthoX(){return __get__(this,
function(self,x){return self.scaleX(x+Math.floor(orthoWidth/2))})},get orthoY(){return __get__(this,function(self,y){return self.scaleY(orthoHeight-Math.floor(fieldHeight/2)-y)})},get keydown(){return __get__(this,function(self,event){self.keyCode=event.keyCode})},get keyup(){return __get__(this,function(self,event){self.keyCode=null})}});export var main=function(){var bpm=80;var feel=.25;var mode="common cycle";var graph_params=gp.rythmologie;var voicings=[4,3,5];var game=Game(bpm,voicings,mode,
feel,graph_params);return null};if(__name__=="__main__")main();

//# sourceMappingURL=RhythmViewer.map